ToDoList/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Domain.Enum;
using ToDoList.Domain.Filters.Task;
using ToDoList.Domain.Response.Interface;
using ToDoList.Domain.ViewModels;
using ToDoList.Services.Interfaces;
using ToDoList.Services.Services;

namespace ToDoList.Controllers
{
    public class TaskController : Controller
    {
        private readonly ILogger<TaskController> _logger;
        private readonly ITaskService _taskService;

        public TaskController(ILogger<TaskController> logger, ITaskService taskService)
        {
            _logger = logger;
            _taskService = taskService;
        }

        public IActionResult Index()
        {
            return View();
        }
                
        [HttpPost]
        public async Task<IActionResult> Create(CreateTaskViewModel model)
        {
            if (model != null)
            {
                _logger.LogInformation($"Описание задачи: {model.Description}; Имя:{model.Name}; Приоритет:{model.Priority}");
                var response = await _taskService.CreateAsync(model);
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return Ok(new { description = response.Description });
                }
            }
            return BadRequest(new { description = "Модель была пуста" });
        }

        public async Task<IActionResult> TaskHandler(TaskFilters taskFilter)
        {

            var priority = HttpContext.Request.Headers["Priority"].ToString();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();

            taskFilter.Priority = (TaskPriority)int.Parse(priority);
            taskFilter.Skip = start != null ? int.Parse(start) : 0;
            taskFilter.PageSize = length != null ? int.Parse(length) : 0;



            var response = await _taskService.GetTasksAsync(taskFilter);
            var data = response.Data as IBaseResponse<IEnumerable<TaskViewModel>>;
            if (data != null && data.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return Json(new { recordsFiltered = response.LengthDataBase, recordsTotal = response.LengthDataBase, data = data.Data });
            }
            return RedirectToAction("Index");    
        }

        [HttpPost]
        public async Task<IActionResult> EndTask(int id)
        {
            var response = await _taskService.CompliteTaskAsync(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return Ok(new { description = "Задача выполнена!"});
            }
            return BadRequest(new { description = "Задача не найдена или произошла ошибка на сервере"});
        }

        [HttpGet]
        public async Task<IActionResult> GetComplitedTasks()
        {
            var response = await _taskService.GetComplitedTasksAsync();
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return Ok(new { data = response.Data });
            }
            return BadRequest(new { description = "Данные не найдены или произошла ошибка на сервере"});
        }

        [HttpGet]
        public async Task<IActionResult> FinishDay()
        {
            var response = await _taskService.FinishTasks();
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                var bytes = new CsvBaseService<IEnumerable<TaskViewModel>>().UploadFile(response.Data);
                return File(bytes,"text/csv",$"Статистика за {DateTime.Now.ToLongDateString()}.csv");
            }
            return BadRequest(new {description = response.Description});
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTask(int id)
        {
            var response = await _taskService.DeleteTaskAsync(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return Ok(new { description = response.Description});
            }
            return BadRequest(new { description = response.Description });
        }
    }
}

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.styles.css" asp-append-version="true" />
    <link href="~/css/datatables.min.css" rel="stylesheet" />
</head>
<body>
    <template>
        <div class="complited-task">
            <h6 id="name">Название задачи: </h6>
            <p id="description" class="text-muted">Описание: </p>
            <p id="datetime">Закончена в: </p>
        </div>
    </template>
    <div class="wrapper">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoList</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Home</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <main class="content">
            <div class="container">
                <div class="content-row">
                    <div class="content-tasks content-column">
                        <div>@RenderBody()</div>
                    </div>
                    <div class="content-layout content-column">
                        <h4>
                            <span class="text-muted">Выполненные задачи</span>
                        </h4>
                    <div id="complitedTasks">
                    </div>
                    <form asp-controller="Task" asp-action="FinishDay" method="get">
                        <button type="submit" class="button">Закончить день</button>
                    </form>
                    <div class="form-group">
                        <label>Заметки для себя</label>
                        <textarea rows="3" class="form-control"></textarea>
                    </div>
                    </div>
                </div>
            </div>
        </main>
        <footer>
            <div class="container">
                &copy; 2023 - ToDoList
            </div>
        </footer>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        const complitedDiv = document.querySelector('#complitedTasks');
        $(document).ready(getComplitedTasks);

        function getComplitedTasks(){
            $.ajax({
                method: 'GET',
                url: "@Url.Action("GetComplitedTasks")",
                data: null,
                success: function (data) {
                    for (let i = 0; i < data.data.length; i++) {
                        let templateCloneTask = document.querySelector('template').content.cloneNode(true);
                        templateCloneTask.querySelector('#name').textContent += `${data.data[i].name}; `;
                        templateCloneTask.querySelector('#description').textContent += `${data.data[i].description}; `;
                        templateCloneTask.querySelector('#datetime').textContent += `${data.data[i].dateTime}; `;
                        complitedDiv.appendChild(templateCloneTask);
                    }
                }
            });
        }
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoList/Views/Task/Index.cshtml
@{
    ViewData["Title"] = "Binokool";
}
<h4 class="mb-3 text-muted">Создание задачи</h4>
<form id="createTaskForm">
    <div class="mb-3">
        <label class="form-label">Название задачи</label>
        <input name="name" type="text" class="form-control"/>
    </div>
    <div class="mb-3">
    <label class="form-label">Приоритет задачи</label>
        <select name="priority" class="form-select mb-3" asp-items="Html.GetEnumSelectList<TaskPriority>()"></select>
    </div>
    <div class="mb-3">
        <label class="form-label">Полное описание задачи</label>
        <textarea name="description" class="form-control" rows="3"></textarea>
    </div>
    <button class="button" id="createTask">Создать</button>
</form>
<br/>
<div class="row">
    <div class="col">
        <label>Приоритет</label>
        <select id="selectPriority" class="form-control" asp-items="Html.GetEnumSelectList<TaskPriority>()">
            <option value="0">Все</option>
        </select>
        <h3 class="text-center">Список незавершенных задач</h3>
        <table class="table table-dark table-hover mt-4 text-center" id="taskTableId">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Приоритет</th>
                    <th>Статус</th>
                    <th>Дата создания</th>
                    <th>Действия</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/datatables.min.js"></script>
    <script>
        let selectedPriority = document.querySelector("#selectPriority").value;
        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-success',
            },
            buttonsStyling: false
        })
        $('#createTask').on('click', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Create","Task")',
                data: $('#createTaskForm').serialize(),
                success: function (response) {
                    Swal.fire({
                        title: 'Информация',
                        text: response.description,
                        icon: 'success',
                        confirmButtonText: 'Окей'
                    });
                    taskTable.draw();
                },
                error: function (response) {
                    Swal.fire({
                        title: 'Информация',
                        text: response.responseJSON.description,
                        icon: 'error',
                        confirmButtonText: 'Окей'
                    })
                }
            })
        });
        let taskTable = $('#taskTableId').DataTable({
            info: false,
            serverSide: true,
            searching: false,
            paging: true,
            sorting: false,
            ajax: {
                url: "@Url.Action("TaskHandler")",
                method:'POST',
                beforeSend: function (xhr) { xhr.setRequestHeader('Priority', `${selectedPriority}`); },
                data: {}
            },
            columns:[
                { data: 'name' },
                { data: 'priority' },
                { data: 'isCompleted' },
                { data: 'dateTime' },
                {
                    data: null,
                    sortable: false,
                    render: function (data, type){
                        return '<button class="btn btn-success btn-sm center-block mb-1">Выполнить</button>'
                    }
                },
                {
                    data: null,
                    sortable: false,
                    render: function (data, type) {
                        return '<button class="btn btn-danger btn-sm center-block mb-1">Удалить</button>'
                    }
                }
            ],
            createdRow: function (nRow,data){
                let compliteTaskHandler = function (message,action){
                    swalWithBootstrapButtons.fire({
                        title: message,
                        icon: 'warning',
                        confirmButtonText: 'Да',
                        reverseButtons: true
                    }).then((result) => {
                        if (result.isConfirmed) {
                            $.ajax({
                                method:'POST',
                                data: {id: data.id},
                                url: action,
                                success: function (data) {
                                    Swal.fire({
                                        title: 'Информация',
                                        text: data.description,
                                        icon: 'success',
                                        confirmButtonText: 'Окей'
                                    });
                                    taskTable.draw();
                                },
                                error: function (data) {
                                    Swal.fire({
                                        title: 'Информация',
                                        text: data.description,
                                        icon: 'error',
                                        confirmButtonText: 'Окей'
                                    });
                                }
                            });
                        }
                    });
                }
                for (var i = 0; i < taskTable.columns().header().length - 1;i++) {
                    $('td', nRow).eq(i).css('cursor', 'pointer');
                    $('td', nRow).eq(i).attr('title', `${data.description}`);
                }
                $('td button.btn-success', nRow).on('click', () => {
                    compliteTaskHandler('Вы действительно хотите выполнить задачу',"@Url.Action("EndTask")");
                });
                $('td button.btn-danger', nRow).on('click', () => {
                    compliteTaskHandler('Вы действительно хотите удалить задачу', "@Url.Action("DeleteTask")");
                });
            }
        });
        
        $('#selectPriority').on('change', function () {
            selectedPriority = document.querySelector("#selectPriority").value;
            taskTable.draw();
        });
    </script>
}